/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        /** Create Manual Job */
        post: operations["create_manual_job_api_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{dedup_hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__dedup_hash__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Applications */
        get: operations["list_applications_api_applications_get"];
        put?: never;
        /** Create Application */
        post: operations["create_application_api_applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{dedup_hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Application */
        delete: operations["delete_application_api_applications__dedup_hash__delete"];
        options?: never;
        head?: never;
        /** Update Application */
        patch: operations["update_application_api_applications__dedup_hash__patch"];
        trace?: never;
    };
    "/api/eval/corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Eval Corrections */
        get: operations["list_eval_corrections_api_eval_corrections_get"];
        put?: never;
        /**
         * Upsert Eval Correction
         * @description Upsert a human correction to a job's skills_fit score.
         *
         *     The server snapshots the current AI score/model/profile_version from
         *     raw.scored_job_postings so the correction stays meaningful even after a
         *     later re-scoring run with different (model, profile_version). Last-write-
         *     wins on dedup_hash.
         */
        post: operations["upsert_eval_correction_api_eval_corrections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/eval/corrections/{dedup_hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Eval Correction */
        get: operations["get_eval_correction_api_eval_corrections__dedup_hash__get"];
        put?: never;
        post?: never;
        /** Delete Eval Correction */
        delete: operations["delete_eval_correction_api_eval_corrections__dedup_hash__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AiFitDetail */
        AiFitDetail: {
            /** Fit Score */
            fit_score?: number | null;
            /** Confidence */
            confidence?: string | null;
            /** Score Rationale */
            score_rationale?: string | null;
            /**
             * Top Matches
             * @default []
             */
            top_matches: string[];
            /**
             * Gaps
             * @default []
             */
            gaps: string[];
            /**
             * Hard Concerns
             * @default []
             */
            hard_concerns: string[];
            /**
             * Core Job Duties
             * @default []
             */
            core_job_duties: string[];
        } & {
            [key: string]: unknown;
        };
        /** Application */
        Application: {
            /** Dedup Hash */
            dedup_hash: string;
            /**
             * Status
             * @enum {string}
             */
            status: "saved" | "maybe" | "to_apply" | "applied" | "screening" | "interview" | "offer" | "rejected" | "withdrawn" | "hired" | "ghosted";
            /** Applied At */
            applied_at: string | null;
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Title */
            title?: string | null;
            /** Company */
            company?: string | null;
            /** Fit Score */
            fit_score?: number | null;
            /** Source Url */
            source_url?: string | null;
        };
        /** ApplicationCreate */
        ApplicationCreate: {
            /** Dedup Hash */
            dedup_hash: string;
            /**
             * Status
             * @default saved
             * @enum {string}
             */
            status: "saved" | "maybe" | "to_apply" | "applied" | "screening" | "interview" | "offer" | "rejected" | "withdrawn" | "hired" | "ghosted";
            /** Applied At */
            applied_at?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** ApplicationUpdate */
        ApplicationUpdate: {
            /** Status */
            status?: ("saved" | "maybe" | "to_apply" | "applied" | "screening" | "interview" | "offer" | "rejected" | "withdrawn" | "hired" | "ghosted") | null;
            /** Applied At */
            applied_at?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** EvalCorrectionIn */
        EvalCorrectionIn: {
            /** Dedup Hash */
            dedup_hash: string;
            /** Corrected Score */
            corrected_score: number;
            /** Correction Reason */
            correction_reason?: string | null;
        };
        /** EvalCorrectionOut */
        EvalCorrectionOut: {
            /** Dedup Hash */
            dedup_hash: string;
            /** Corrected Score */
            corrected_score: number;
            /** Correction Reason */
            correction_reason: string | null;
            /** Original Score */
            original_score: number | null;
            /** Original Model */
            original_model: string;
            /** Profile Version */
            profile_version: string;
            /**
             * Corrected At
             * Format: date-time
             */
            corrected_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobDetail */
        JobDetail: {
            /** Dedup Hash */
            dedup_hash: string;
            /** Source */
            source: string | null;
            /** Source Job Id */
            source_job_id: string | null;
            /** Source Url */
            source_url: string | null;
            /** Title */
            title: string | null;
            /** Company */
            company: string | null;
            /** Location */
            location: string | null;
            /** Posted At */
            posted_at: string | null;
            /** Description */
            description: string | null;
            /** Scraped At */
            scraped_at: string | null;
            /** Remote Classification */
            remote_classification: string | null;
            /** Salary Min Usd */
            salary_min_usd: number | null;
            /** Salary Max Usd */
            salary_max_usd: number | null;
            /** Salary Period */
            salary_period: string | null;
            /** Fit Score */
            fit_score: number | null;
            /** Confidence */
            confidence: string | null;
            /** Score Rationale */
            score_rationale: string | null;
            ai_fit_detail: components["schemas"]["AiFitDetail"] | null;
            /** Pipeline Metadata */
            pipeline_metadata: {
                [key: string]: unknown;
            };
            /** Run Id */
            run_id: string;
            /**
             * Scored At
             * Format: date-time
             */
            scored_at: string;
            /** Model */
            model: string;
            /** Provider */
            provider: string;
            /** Profile Version */
            profile_version: string;
            /** Failure Reason */
            failure_reason: string | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Ingested At
             * Format: date-time
             */
            ingested_at: string;
        };
        /** JobListResponse */
        JobListResponse: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Items */
            items: components["schemas"]["JobSummary"][];
        };
        /** JobSummary */
        JobSummary: {
            /** Dedup Hash */
            dedup_hash: string;
            /** Source */
            source: string | null;
            /** Source Url */
            source_url: string | null;
            /** Title */
            title: string | null;
            /** Company */
            company: string | null;
            /** Location */
            location: string | null;
            /** Posted At */
            posted_at: string | null;
            /** Remote Classification */
            remote_classification: string | null;
            /** Salary Min Usd */
            salary_min_usd: number | null;
            /** Salary Max Usd */
            salary_max_usd: number | null;
            /** Salary Period */
            salary_period: string | null;
            /** Fit Score */
            fit_score: number | null;
            /** Confidence */
            confidence: string | null;
            /** Score Rationale */
            score_rationale: string | null;
            /** Failure Reason */
            failure_reason: string | null;
            /**
             * Scored At
             * Format: date-time
             */
            scored_at: string;
        };
        /** ManualJobCreate */
        ManualJobCreate: {
            /** Title */
            title: string;
            /** Fit Score */
            fit_score: number;
            /** Company */
            company?: string | null;
            /** Source Url */
            source_url?: string | null;
            /** Description */
            description?: string | null;
            /** Location */
            location?: string | null;
            /** Posted At */
            posted_at?: string | null;
            /**
             * Status
             * @default saved
             * @enum {string}
             */
            status: "saved" | "maybe" | "to_apply" | "applied" | "screening" | "interview" | "offer" | "rejected" | "withdrawn" | "hired" | "ghosted";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                min_score?: number | null;
                max_score?: number | null;
                remote_classification?: ("fully_remote" | "remote_with_quarterly_travel" | "remote_with_monthly_travel" | "remote_with_frequent_travel" | "hybrid" | "onsite_disguised" | "location_restricted" | "unclear")[] | null;
                min_posted_at?: string | null;
                max_posted_at?: string | null;
                min_salary_usd?: number | null;
                search?: string | null;
                company?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_manual_job_api_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualJobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__dedup_hash__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dedup_hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_applications_api_applications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"][];
                };
            };
        };
    };
    create_application_api_applications_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_application_api_applications__dedup_hash__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dedup_hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_application_api_applications__dedup_hash__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dedup_hash: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_eval_corrections_api_eval_corrections_get: {
        parameters: {
            query?: {
                model?: string | null;
                profile_version?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalCorrectionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_eval_correction_api_eval_corrections_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvalCorrectionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalCorrectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_eval_correction_api_eval_corrections__dedup_hash__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dedup_hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalCorrectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_eval_correction_api_eval_corrections__dedup_hash__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dedup_hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
