/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        /** Create Manual Job */
        post: operations["create_manual_job_api_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{dedup_hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__dedup_hash__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Applications */
        get: operations["list_applications_api_applications_get"];
        put?: never;
        /** Create Application */
        post: operations["create_application_api_applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{dedup_hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Application */
        delete: operations["delete_application_api_applications__dedup_hash__delete"];
        options?: never;
        head?: never;
        /** Update Application */
        patch: operations["update_application_api_applications__dedup_hash__patch"];
        trace?: never;
    };
    "/api/applications/{dedup_hash}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_api_applications__dedup_hash__events_get"];
        put?: never;
        /**
         * Create Event
         * @description Create an application event. Accepts the discriminated union
         *     (StatusChangeEvent | GenericEvent) and persists it row-by-row.
         */
        post: operations["create_event_api_applications__dedup_hash__events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{dedup_hash}/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Event */
        delete: operations["delete_event_api_applications__dedup_hash__events__event_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Event
         * @description Patch an application event. Allowed fields: occurred_at, body, tags, metadata.
         */
        patch: operations["update_event_api_applications__dedup_hash__events__event_id__patch"];
        trace?: never;
    };
    "/api/eval/corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Eval Corrections */
        get: operations["list_eval_corrections_api_eval_corrections_get"];
        put?: never;
        /**
         * Upsert Eval Correction
         * @description Upsert the current user's correction to their skills_fit score.
         *
         *     The server snapshots the user's own score/model/profile_version from
         *     raw.job_scores so the correction stays meaningful even after a later
         *     re-scoring run with different (model, profile_version). Last-write-wins
         *     per (user, job).
         */
        post: operations["upsert_eval_correction_api_eval_corrections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/eval/corrections/{dedup_hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Eval Correction */
        get: operations["get_eval_correction_api_eval_corrections__dedup_hash__get"];
        put?: never;
        post?: never;
        /** Delete Eval Correction */
        delete: operations["delete_eval_correction_api_eval_corrections__dedup_hash__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description The authenticated user's own record — drives role-aware frontend UI.
         */
        get: operations["get_me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Profile */
        put: operations["put_profile_api_settings_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Search */
        put: operations["put_search_api_settings_search_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/pipeline-enabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Pipeline Enabled */
        put: operations["put_pipeline_enabled_api_settings_pipeline_enabled_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/alert-thresholds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Alert Thresholds */
        put: operations["put_alert_thresholds_api_settings_alert_thresholds_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/upcoming-steps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Upcoming Steps */
        get: operations["get_upcoming_steps_api_upcoming_steps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AiFitDetail */
        AiFitDetail: {
            /** Fit Score */
            fit_score?: number | null;
            /** Confidence */
            confidence?: string | null;
            /** Score Rationale */
            score_rationale?: string | null;
            /**
             * Top Matches
             * @default []
             */
            top_matches: string[];
            /**
             * Gaps
             * @default []
             */
            gaps: string[];
            /**
             * Hard Concerns
             * @default []
             */
            hard_concerns: string[];
            /**
             * Core Job Duties
             * @default []
             */
            core_job_duties: string[];
        } & {
            [key: string]: unknown;
        };
        /** AlertThresholdsResponse */
        AlertThresholdsResponse: {
            /** Stale To Apply Days */
            stale_to_apply_days: number;
            /** Post Interview Nudge Days */
            post_interview_nudge_days: number;
            /** Post Application Nudge Days */
            post_application_nudge_days: number;
            /** Inactivity Days */
            inactivity_days: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * AlertThresholdsUpdate
         * @description Per-user alert threshold settings (days). Load-bearing for rules engine.
         */
        AlertThresholdsUpdate: {
            /** Stale To Apply Days */
            stale_to_apply_days: number;
            /** Post Interview Nudge Days */
            post_interview_nudge_days: number;
            /** Post Application Nudge Days */
            post_application_nudge_days: number;
            /** Inactivity Days */
            inactivity_days: number;
        };
        /** Application */
        Application: {
            /** Dedup Hash */
            dedup_hash: string;
            /**
             * Status
             * @enum {string}
             */
            status: "maybe" | "to_apply" | "applied" | "screening" | "interview" | "offer" | "rejected" | "candidate_withdrew" | "hired" | "ghosted" | "passed";
            /** Applied At */
            applied_at: string | null;
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Title */
            title?: string | null;
            /** Company */
            company?: string | null;
            /** Fit Score */
            fit_score?: number | null;
            /** Source Url */
            source_url?: string | null;
            latest_event?: components["schemas"]["LatestEvent"] | null;
        };
        /** ApplicationCreate */
        ApplicationCreate: {
            /** Dedup Hash */
            dedup_hash: string;
            /**
             * Status
             * @default maybe
             * @enum {string}
             */
            status: "maybe" | "to_apply" | "applied" | "screening" | "interview" | "offer" | "rejected" | "candidate_withdrew" | "hired" | "ghosted" | "passed";
            /** Applied At */
            applied_at?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * ApplicationEvent
         * @description Full output model returned by the API (all stored columns).
         */
        ApplicationEvent: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Dedup Hash */
            dedup_hash: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "status_change" | "event";
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Body */
            body: string | null;
            /** Tags */
            tags: string[];
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ApplicationEventUpdate
         * @description PATCH payload — all fields optional; only those set are written
         *     (``model_dump(exclude_unset=True)``). Typed so bad shapes fail at the edge.
         */
        ApplicationEventUpdate: {
            /** Occurred At */
            occurred_at?: string | null;
            /** Body */
            body?: string | null;
            /** Tags */
            tags?: string[] | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /** ApplicationUpdate */
        ApplicationUpdate: {
            /** Status */
            status?: ("maybe" | "to_apply" | "applied" | "screening" | "interview" | "offer" | "rejected" | "candidate_withdrew" | "hired" | "ghosted" | "passed") | null;
            /** Applied At */
            applied_at?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * CandidateProfileInput
         * @description One user's filled-in candidate_profile.yml.template.
         *
         *     ``profile_version`` is accepted (the template carries the field, so
         *     filled-in copies will have it) but ignored everywhere: the authoritative
         *     version is the content hash computed on save (spec §2).
         *
         *     ``evidence`` and ``scoring_notes`` are stored but not yet emitted into
         *     the pipeline profile — wiring them into the skills_fit prompt is a
         *     scoring-contract change that needs its own eval pass.
         */
        CandidateProfileInput: {
            /** Profile Version */
            profile_version?: string | null;
            /** Summary */
            summary: string;
            /** Level */
            level: string;
            /** Education */
            education?: string[];
            /** Core Skills */
            core_skills: string[];
            /** Adjacent Skills */
            adjacent_skills?: string[];
            /** Growth Skills */
            growth_skills?: string[];
            /** Preferred Domains */
            preferred_domains?: string[];
            /** Avoided Domains */
            avoided_domains?: string[];
            constraints?: components["schemas"]["Constraints"];
            evidence?: components["schemas"]["Evidence"] | null;
            /** Scoring Notes */
            scoring_notes?: string | null;
        };
        /** Constraints */
        Constraints: {
            /** Hard */
            hard?: string[];
            /** Soft */
            soft?: string[];
        };
        /** EmploymentTypes */
        EmploymentTypes: {
            /** Acceptable */
            acceptable?: ("fulltime" | "parttime" | "contract")[];
        };
        /** EvalCorrectionIn */
        EvalCorrectionIn: {
            /** Dedup Hash */
            dedup_hash: string;
            /** Corrected Score */
            corrected_score: number;
            /** Correction Reason */
            correction_reason?: string | null;
        };
        /** EvalCorrectionOut */
        EvalCorrectionOut: {
            /** Dedup Hash */
            dedup_hash: string;
            /** Corrected Score */
            corrected_score: number;
            /** Correction Reason */
            correction_reason: string | null;
            /** Original Score */
            original_score: number | null;
            /** Original Model */
            original_model: string;
            /** Profile Version */
            profile_version: string;
            /**
             * Corrected At
             * Format: date-time
             */
            corrected_at: string;
        };
        /** Evidence */
        Evidence: {
            /** Projects */
            projects?: components["schemas"]["EvidenceProject"][];
            /** Publications Or Writing Samples */
            publications_or_writing_samples?: components["schemas"]["EvidenceWriting"][];
            /** Engineering Artifacts */
            engineering_artifacts?: components["schemas"]["EvidenceArtifact"][];
        };
        /** EvidenceArtifact */
        EvidenceArtifact: {
            /** Name */
            name: string;
            /** Evidence Of */
            evidence_of?: string[];
        } & {
            [key: string]: unknown;
        };
        /** EvidenceProject */
        EvidenceProject: {
            /** Name */
            name: string;
            /**
             * Summary
             * @default
             */
            summary: string;
            /** Evidence Of */
            evidence_of?: string[];
        } & {
            [key: string]: unknown;
        };
        /** EvidenceWriting */
        EvidenceWriting: {
            /** Title */
            title: string;
            /** Evidence Of */
            evidence_of?: string[];
        } & {
            [key: string]: unknown;
        };
        /**
         * GenericEvent
         * @description Free-form event — meaning carried by tags[] (ECS-style).
         */
        GenericEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "event";
            /** Body */
            body?: string | null;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /**
             * Metadata
             * @default {}
             */
            metadata: {
                [key: string]: unknown;
            };
            /** Occurred At */
            occurred_at?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HomeLocation */
        HomeLocation: {
            /** City */
            city: string;
            /** Region */
            region: string;
            /**
             * Country
             * @default US
             */
            country: string;
        };
        /**
         * InactivityAlertOut
         * @description No *applied* event across the pipeline for > threshold days.
         */
        InactivityAlertOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "inactivity";
            /** Message */
            message: string;
            /** Days */
            days: number;
        };
        /** IndustriesAndDomains */
        IndustriesAndDomains: {
            /** Preferred */
            preferred?: string[];
            /** Excluded */
            excluded?: string[];
        };
        /** JobDetail */
        JobDetail: {
            /** Dedup Hash */
            dedup_hash: string;
            /** Source */
            source: string | null;
            /** Source Job Id */
            source_job_id: string | null;
            /** Source Url */
            source_url: string | null;
            /** Title */
            title: string | null;
            /** Company */
            company: string | null;
            /** Location */
            location: string | null;
            /** Posted At */
            posted_at: string | null;
            /** Description */
            description: string | null;
            /** Scraped At */
            scraped_at: string | null;
            /** Remote Classification */
            remote_classification: string | null;
            /** Salary Min Usd */
            salary_min_usd: number | null;
            /** Salary Max Usd */
            salary_max_usd: number | null;
            /** Salary Period */
            salary_period: string | null;
            /** Fit Score */
            fit_score: number | null;
            /** Confidence */
            confidence: string | null;
            /** Score Rationale */
            score_rationale: string | null;
            ai_fit_detail: components["schemas"]["AiFitDetail"] | null;
            /** Pipeline Metadata */
            pipeline_metadata: {
                [key: string]: unknown;
            };
            /** Run Id */
            run_id: string;
            /**
             * Scored At
             * Format: date-time
             */
            scored_at: string;
            /** Model */
            model: string;
            /** Provider */
            provider: string;
            /** Profile Version */
            profile_version: string;
            /** Failure Reason */
            failure_reason: string | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Ingested At
             * Format: date-time
             */
            ingested_at: string;
        };
        /** JobListResponse */
        JobListResponse: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Items */
            items: components["schemas"]["JobSummary"][];
        };
        /** JobSummary */
        JobSummary: {
            /** Dedup Hash */
            dedup_hash: string;
            /** Source */
            source: string | null;
            /** Source Url */
            source_url: string | null;
            /** Title */
            title: string | null;
            /** Company */
            company: string | null;
            /** Location */
            location: string | null;
            /** Posted At */
            posted_at: string | null;
            /** Remote Classification */
            remote_classification: string | null;
            /** Salary Min Usd */
            salary_min_usd: number | null;
            /** Salary Max Usd */
            salary_max_usd: number | null;
            /** Salary Period */
            salary_period: string | null;
            /** Fit Score */
            fit_score: number | null;
            /** Confidence */
            confidence: string | null;
            /** Score Rationale */
            score_rationale: string | null;
            /** Failure Reason */
            failure_reason: string | null;
            /**
             * Scored At
             * Format: date-time
             */
            scored_at: string;
        };
        /** Keywords */
        Keywords: {
            /** Required Any */
            required_any?: string[];
            /** Required All */
            required_all?: string[];
            /** Preferred */
            preferred?: string[];
            /** Excluded */
            excluded?: string[];
        };
        /**
         * LatestEvent
         * @description Most-recent activity for a job — display-only summary for the
         *     Tracking list. Inert: rendered, never queried.
         */
        LatestEvent: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "status_change" | "event";
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Body */
            body?: string | null;
            /** To Status */
            to_status?: ("maybe" | "to_apply" | "applied" | "screening" | "interview" | "offer" | "rejected" | "candidate_withdrew" | "hired" | "ghosted" | "passed") | null;
        };
        /** Location */
        Location: {
            /** City */
            city: string;
            /** Region */
            region: string;
            /**
             * Country
             * @default US
             */
            country: string;
        };
        /** Locations */
        Locations: {
            /** Acceptable */
            acceptable?: components["schemas"]["Location"][];
            /** Preferred */
            preferred?: components["schemas"]["Location"][];
            /** Excluded */
            excluded?: components["schemas"]["Location"][];
            relocation?: components["schemas"]["Relocation"];
        };
        /** ManualJobCreate */
        ManualJobCreate: {
            /** Title */
            title: string;
            /** Fit Score */
            fit_score: number;
            /** Company */
            company?: string | null;
            /** Source Url */
            source_url?: string | null;
            /** Description */
            description?: string | null;
            /** Location */
            location?: string | null;
            /** Posted At */
            posted_at?: string | null;
            /**
             * Status
             * @default maybe
             * @enum {string}
             */
            status: "maybe" | "to_apply" | "applied" | "screening" | "interview" | "offer" | "rejected" | "candidate_withdrew" | "hired" | "ghosted" | "passed";
        };
        /** Organizations */
        Organizations: {
            /** Target Companies */
            target_companies?: string[];
            /** Similar To */
            similar_to?: string[];
            /** Preferred Organization Types */
            preferred_organization_types?: string[];
        };
        /** PipelineEnabledResponse */
        PipelineEnabledResponse: {
            /** Pipeline Enabled */
            pipeline_enabled: boolean;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PipelineEnabledUpdate */
        PipelineEnabledUpdate: {
            /** Enabled */
            enabled: boolean;
        };
        /**
         * PostApplicationAlertOut
         * @description Jobs in *applied*\/*screening* with no follow-up for > threshold days.
         */
        PostApplicationAlertOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "post_application";
            /** Message */
            message: string;
            /** Count */
            count: number;
            /** Dedup Hashes */
            dedup_hashes: string[];
            /** Days */
            days: number;
        };
        /**
         * PostInterviewAlertOut
         * @description Jobs that entered *interview* and haven't progressed past threshold.
         */
        PostInterviewAlertOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "post_interview";
            /** Message */
            message: string;
            /** Count */
            count: number;
            /** Dedup Hashes */
            dedup_hashes: string[];
            /** Days */
            days: number;
        };
        /** ProfileSaveResponse */
        ProfileSaveResponse: {
            /** Profile Version */
            profile_version: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** Relocation */
        Relocation: {
            /**
             * Willing
             * @default false
             */
            willing: boolean;
        };
        /** Roles */
        Roles: {
            target_titles: components["schemas"]["TargetTitles"];
            /** Excluded Titles */
            excluded_titles?: string[];
        };
        /** ScrapePreferences */
        ScrapePreferences: {
            /**
             * Include Remote National Searches
             * @default true
             */
            include_remote_national_searches: boolean;
            /**
             * Include Local Searches
             * @default true
             */
            include_local_searches: boolean;
            /**
             * Include Company Board Searches
             * @default true
             */
            include_company_board_searches: boolean;
            /**
             * Include General Job Boards
             * @default true
             */
            include_general_job_boards: boolean;
            /**
             * Max Results Per Task
             * @default 50
             */
            max_results_per_task: number;
            /**
             * Freshness Hours
             * @default 48
             */
            freshness_hours: number;
            /**
             * Cadence
             * @default daily
             * @enum {string}
             */
            cadence: "daily" | "weekly";
            /** Salary Floor K */
            salary_floor_k?: (40 | 60 | 80 | 100 | 120) | null;
            /** Linkedin Experience Codes */
            linkedin_experience_codes?: ("1" | "2" | "3" | "4" | "5" | "6")[];
        };
        /**
         * SearchConfigInput
         * @description One user's filled-in job_search_template.yml.
         */
        SearchConfigInput: {
            user: components["schemas"]["UserSection"];
            search_profile: components["schemas"]["SearchProfileMeta"];
            roles: components["schemas"]["Roles"];
            work_constraints?: components["schemas"]["WorkConstraints"];
            locations?: components["schemas"]["Locations"];
            organizations?: components["schemas"]["Organizations"];
            industries_and_domains?: components["schemas"]["IndustriesAndDomains"];
            keywords?: components["schemas"]["Keywords"];
            scrape_preferences?: components["schemas"]["ScrapePreferences"];
        };
        /** SearchProfileMeta */
        SearchProfileMeta: {
            /** Name */
            name: string;
            /**
             * Status
             * @default active
             * @enum {string}
             */
            status: "active" | "paused";
            /**
             * Goal Summary
             * @default
             */
            goal_summary: string;
            /**
             * Search Mode
             * @default balanced
             * @enum {string}
             */
            search_mode: "focused" | "balanced" | "broad";
        };
        /** SearchSaveResponse */
        SearchSaveResponse: {
            /** Policies */
            policies: {
                [key: string]: unknown;
            };
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * SettingsResponse
         * @description Both payloads + versioning. Null payloads = not yet configured, which
         *     the frontend renders as the onboarding state.
         */
        SettingsResponse: {
            /** Profile */
            profile?: {
                [key: string]: unknown;
            } | null;
            /** Profile Version */
            profile_version?: string | null;
            /** Profile Updated At */
            profile_updated_at?: string | null;
            /** Search */
            search?: {
                [key: string]: unknown;
            } | null;
            /** Policies */
            policies?: {
                [key: string]: unknown;
            } | null;
            /** Search Updated At */
            search_updated_at?: string | null;
            /** Pipeline Enabled */
            pipeline_enabled?: boolean | null;
            /** Stale To Apply Days */
            stale_to_apply_days?: number | null;
            /** Post Interview Nudge Days */
            post_interview_nudge_days?: number | null;
            /** Post Application Nudge Days */
            post_application_nudge_days?: number | null;
            /** Inactivity Days */
            inactivity_days?: number | null;
        };
        /**
         * StaleToApplyAlertOut
         * @description Jobs sitting in *to_apply* longer than threshold without moving to *applied*.
         */
        StaleToApplyAlertOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "stale_to_apply";
            /** Message */
            message: string;
            /** Count */
            count: number;
            /** Dedup Hashes */
            dedup_hashes: string[];
            /** Days */
            days: number;
        };
        /**
         * StatusChangeEvent
         * @description Auto-emitted on every status transition. {from, to} is load-bearing
         *     for Phase 21 alerts (derive timing from it).
         */
        StatusChangeEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "status_change";
            /** From */
            from?: ("maybe" | "to_apply" | "applied" | "screening" | "interview" | "offer" | "rejected" | "candidate_withdrew" | "hired" | "ghosted" | "passed") | null;
            /**
             * To
             * @enum {string}
             */
            to: "maybe" | "to_apply" | "applied" | "screening" | "interview" | "offer" | "rejected" | "candidate_withdrew" | "hired" | "ghosted" | "passed";
            /** Occurred At */
            occurred_at?: string | null;
        };
        /** TargetTitles */
        TargetTitles: {
            /** Preferred */
            preferred: string[];
            /** Exploratory */
            exploratory?: string[];
        };
        /**
         * UpcomingStepsResponse
         * @description List of time-based alerts derived from the user's application events.
         */
        UpcomingStepsResponse: {
            /** Alerts */
            alerts: (components["schemas"]["StaleToApplyAlertOut"] | components["schemas"]["PostInterviewAlertOut"] | components["schemas"]["InactivityAlertOut"] | components["schemas"]["PostApplicationAlertOut"])[];
        };
        /** User */
        User: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name?: string | null;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "member";
        };
        /** UserSection */
        UserSection: {
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            home_location?: components["schemas"]["HomeLocation"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkArrangement */
        WorkArrangement: {
            /**
             * Acceptable
             * @default true
             */
            acceptable: boolean;
            /**
             * Preferred
             * @default false
             */
            preferred: boolean;
            /**
             * Required
             * @default false
             */
            required: boolean;
        };
        /** WorkArrangements */
        WorkArrangements: {
            remote?: components["schemas"]["WorkArrangement"];
            hybrid?: components["schemas"]["WorkArrangement"];
            onsite?: components["schemas"]["WorkArrangement"];
        };
        /** WorkConstraints */
        WorkConstraints: {
            employment_types?: components["schemas"]["EmploymentTypes"];
            work_arrangements?: components["schemas"]["WorkArrangements"];
            /** Max Travel Days */
            max_travel_days?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                min_score?: number | null;
                max_score?: number | null;
                remote_classification?: ("fully_remote" | "remote_with_quarterly_travel" | "remote_with_monthly_travel" | "remote_with_frequent_travel" | "hybrid" | "onsite_disguised" | "location_restricted" | "unclear")[] | null;
                min_posted_at?: string | null;
                max_posted_at?: string | null;
                min_salary_usd?: number | null;
                search?: string | null;
                company?: string | null;
                sort?: "fit_score" | "posted_at" | "company" | "title" | "salary_min_usd";
                order?: "asc" | "desc";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_manual_job_api_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualJobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__dedup_hash__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dedup_hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_applications_api_applications_get: {
        parameters: {
            query?: {
                status?: ("maybe" | "to_apply" | "applied" | "screening" | "interview" | "offer" | "rejected" | "candidate_withdrew" | "hired" | "ghosted" | "passed")[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_application_api_applications_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_application_api_applications__dedup_hash__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dedup_hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_application_api_applications__dedup_hash__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dedup_hash: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_api_applications__dedup_hash__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dedup_hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_event_api_applications__dedup_hash__events_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dedup_hash: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusChangeEvent"] | components["schemas"]["GenericEvent"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_event_api_applications__dedup_hash__events__event_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dedup_hash: string;
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_event_api_applications__dedup_hash__events__event_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dedup_hash: string;
                event_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationEventUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_eval_corrections_api_eval_corrections_get: {
        parameters: {
            query?: {
                model?: string | null;
                profile_version?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalCorrectionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_eval_correction_api_eval_corrections_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvalCorrectionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalCorrectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_eval_correction_api_eval_corrections__dedup_hash__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dedup_hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalCorrectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_eval_correction_api_eval_corrections__dedup_hash__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dedup_hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    put_profile_api_settings_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateProfileInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileSaveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_search_api_settings_search_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchConfigInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchSaveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_pipeline_enabled_api_settings_pipeline_enabled_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PipelineEnabledUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineEnabledResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_alert_thresholds_api_settings_alert_thresholds_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertThresholdsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertThresholdsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_upcoming_steps_api_upcoming_steps_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpcomingStepsResponse"];
                };
            };
        };
    };
}
